### ISSUE TITLE
db_duckdb feedback?

### ISSUE THREAD

**Issue by sdmcallister** [Clonkk/duckdb_wrapper#1]
Thank you very much for creating this example wrapper! I am planning to continue to build upon this wrapper and hope to release a nimble package once duckdb reaches version 1.x.  Ideally, I would like to provide procs similar to the db_sqlite library. Would it be possible to occasionally receive some feedback (here or elsewhere) as I work on adding some functionality?

**Comment by Clonkk** [comment]
Sorry I just saw this issue.

Yes, I can give you feedback on bindings C library but I've never used DuckDB.

IMO, if you plan on putting work into it I would create a dedicated repo (you can use files from this one as a base if you want) since this repo generate the bindings from scratch it won't be suited to adding things (I only included the generated file as examples of a potential output). 

I also won't be maintaining this repo since I madeit purely as an exercise that can eventually be used for PoC.

If you want to wrap with  SQLite API you can directly wrap : https://github.com/duckdb/duckdb/tree/master/tools/sqlite3_api_wrapper

Or you can implement a Nim SQLite API using DuckDb wrapper, in which case [ndb](https://github.com/xzfc/ndb.nim/blob/master/ndb/sqlite.nim) would be a good starting point.

And since [norm](https://github.com/moigagoo/norm) - a great Nim ORM - is based on ndb you could eventually have a powerful DuckDb ORM with a moderate amount of work.

**Comment by sdmcallister** [comment]
That is awesome, thank you.

I'm experimenting a bit more now since `duckdb_free` as added which seems to resolve some of my earlier concerns around `free`. I think I would like to wait until duckdb hits version 1.0.0 before getting really serious as the way data is stored on disc keeps changing with each pre 1.0.0 release. 

I'll definitely look into ndb as well.

**Comment by Clonkk** [comment]
> I think I would like to wait until duckdb hits version 1.0.0 before getting really serious as the way data is stored on disc keeps changing with each pre 1.0.0 

Do you expect the duckdb API to change ? If not, wrapping a C / C++ library only uses the public API of the lib - the underlying implementation shouldn't affect you too much.

**Comment by sdmcallister** [comment]
Good point though I do though expect some other changes to occur. The C api just recently added configuration to allow for multiple read only connections similar to the python api.  Not sure what else is planned.

**Comment by sdmcallister** [comment]
@Clonkk 

You're right though that the core C API is likely to remain stable.

What are your thoughts on using the approach/conventions similar to std/db_sqlite? For instance using mostly `seq[Row]` or basically `seq[seq[string]]`?

I've been trying out the wrapper (from duckdb 0.2.8) with Jester and it has been working well. I want to make sure that I properly close the db and I've had mixed results as noted below using `exitprocs.addExitProc` with `threads:on`. 

The connections are threadsafe so I think it should work well with Jester/httpbeast. 

```
import jester
import duckdb_wrapper
import std/exitprocs

var dbconfig: duckdb_config
if (duckdb_create_config(dbconfig.addr) == DuckDBError):
    echo "Error: Couldn't create config"
    quit(1)

if (duckdb_set_config(dbconfig, "access_mode", "READ_WRITE") == DuckDBError):
    echo "Error: Couldn't set config"
    quit(1)

var db: duckdb_database
if (duckdb_open_ext("test.db", db.addr, dbconfig, nil) == DuckDBError):
    echo "Error: Couldn't Open with config"
    quit(1)
duckdb_destroy_config(dbconfig.addr) # once open can be destroyed

proc atExit(){.noconv.} =
    duckdb_close(addr(db))
    echo "bye"
    quit(0)
exitprocs.addExitProc(atExit) 
setControlCHook(atExit) # when I compile with threads:on this is required, addExitProc doesn't consistently work.

routes:
    get "/":
        var con: duckdb_connection
        if (duckdb_connect(db, con.addr) == DuckDBError):
            resp "Error: couldn't connect"

        var res: duckdb_result
        if duckdb_query(con, "SELECT * FROM integers", addr(res)) == DuckDBError:
            duckdb_disconnect(addr(con))
            resp "Error: Query failed"

        var qvals: seq[string]
        for row in 0..<res.row_count:
            for col in 0..<res.column_count:
                let val = duckdb_value_varchar(addr(res), col, row)
                qvals.add($val)
                duckdb_free(val)
        duckdb_destroy_result(addr(res))
        duckdb_disconnect(addr(con))
        resp "Values: " & $qvals
```

**Comment by Clonkk** [comment]
If you were to create a higher level API based on the wrapper, I would target  https://github.com/xzfc/ndb.nim.
It's fairly similar but improved on stdlib. Eventually the goal would be to add duckdb to https://github.com/moigagoo/norm

Regarding atExitProc, if you consider acceptable to keep the connection open for the full duration of the process then it should work

Otherwise, you can use ``defer`` in the scope of your connection. The manual has more info on defer but basically it's a try-catch-finally in your local scope : 
```nim
block: 
  db.open()
  defer: db.close()
  db.query(...) # do stuff 
```

I've done a PoC as well using sqlite API of duckdb for integrating duckdb into Norm (https://github.com/moigagoo/norm), but I don't know if the sqlite API has the same perf as the "native API".

Some stuff is still missing as well that makes it hard to use : 
* release of the sqlite API shared library (building manually isn't satisfying for wrapper).
* No FOREIGN KEY support

**Comment by sdmcallister** [comment]
@Clonkk 

This performance seems pretty good to me using jester/httpbeast/duckdb! Still using the C api.  500,000 row csv in about 1.13 sec downloaded. 

```
get "/duckdbtest":
    var con: duckdb_connection
    if (duckdb_connect(duckdbinst, con.addr) == DuckDBError):
        resp "Error: couldn't connect"
    var res: duckdb_result
    if duckdb_query(con, "SELECT col1, col2, col3, col4, col5 FROM table LIMIT 500000", addr(res)) == DuckDBError:
        duckdb_disconnect(addr(con))
        resp "Error: Query failed"

  var qvals = ""
    for col in 0..<res.column_count:
      var val = duckdb_column_name(addr(res), col)
      qvals.add($val)
      qvals.add(",")
    qvals.setLen(len(qvals) - 1)
    
    for row in 0..<res.row_count:
      qvals.add("\n")
      for col in 0..<res.column_count:
        let val = duckdb_value_varchar(addr(res), col, row)
        qvals.add($val)
        qvals.add(",")
        duckdb_free(val)
      qvals.setLen(len(qvals) - 1)
    duckdb_destroy_result(addr(res))
    duckdb_disconnect(addr(con))
    resp Http200, {"Content-Type": "text/csv"}, qvals
```
